/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NeuBackdrop {}
  interface NeuModal {
    'footer': boolean;
    'header': boolean;
    'openModal': () => Promise<void>;
    'showcancel': boolean;
    'showcancelicon': boolean;
    'size': string;
  }
}

declare global {


  interface HTMLNeuBackdropElement extends Components.NeuBackdrop, HTMLStencilElement {}
  var HTMLNeuBackdropElement: {
    prototype: HTMLNeuBackdropElement;
    new (): HTMLNeuBackdropElement;
  };

  interface HTMLNeuModalElement extends Components.NeuModal, HTMLStencilElement {}
  var HTMLNeuModalElement: {
    prototype: HTMLNeuModalElement;
    new (): HTMLNeuModalElement;
  };
  interface HTMLElementTagNameMap {
    'neu-backdrop': HTMLNeuBackdropElement;
    'neu-modal': HTMLNeuModalElement;
  }
}

declare namespace LocalJSX {
  interface NeuBackdrop extends JSXBase.HTMLAttributes<HTMLNeuBackdropElement> {}
  interface NeuModal extends JSXBase.HTMLAttributes<HTMLNeuModalElement> {
    'footer'?: boolean;
    'header'?: boolean;
    'onOnModalClose'?: (event: CustomEvent<any>) => void;
    'showcancel'?: boolean;
    'showcancelicon'?: boolean;
    'size'?: string;
  }

  interface IntrinsicElements {
    'neu-backdrop': NeuBackdrop;
    'neu-modal': NeuModal;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


