/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface NeuButton {
    'buttonStyle': string;
    'disabled': boolean;
    'size': string;
    'type': string;
  }
}

declare global {


  interface HTMLNeuButtonElement extends Components.NeuButton, HTMLStencilElement {}
  var HTMLNeuButtonElement: {
    prototype: HTMLNeuButtonElement;
    new (): HTMLNeuButtonElement;
  };
  interface HTMLElementTagNameMap {
    'neu-button': HTMLNeuButtonElement;
  }
}

declare namespace LocalJSX {
  interface NeuButton extends JSXBase.HTMLAttributes<HTMLNeuButtonElement> {
    'buttonStyle'?: string;
    'disabled'?: boolean;
    'size'?: string;
    'type'?: string;
  }

  interface IntrinsicElements {
    'neu-button': NeuButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


